---
- hosts: all
  become: yes
  tasks:
   - name: Install the web server
     apt:
      name: apache2
      state: present
     when: the VM is == "Redhat"
   - name: Start the webserver service
     service:
      name: apache2
      state: started   
     when: the VM is == "Redhat"   