---
- hosts: webservers
  become: yes
  tasks:
   - name: Install the web server
     apt:
      name: "{{ubuntuwebserver}}"

      state: present
     when: ansible_os_family == "Debian"
   - name: Start the webserver service
     service:
      name: apache2
      state: started   
     when: ansible_os_family == "Debian"   